### ISSUE TITLE
Example fails

### ISSUE THREAD

**Issue by Unaimend** [hklarner/detection_of_markers_for_discrete_phenotypes#1]
`biomarkers problem-create --problem emt_problem.json --bnet selvaggio_emt --phenotype AJ_b1=0,AJ_b2=0` fails for me with following error message 
`/home/td/.local/lib/python3.10/site-packages/pydantic/_internal/_config.py:334: UserWarning: Valid config keys have changed in V2:  'keep_untouched' has been renamed to 'ignored_types'
  warnings.warn(message, UserWarning)
failed to create marker detection problem: error=1 validation error for Problem
phenotype_components
  Field required [type=missing, input_value={'primes': {'AJ_b1': [[{'...subspace': {0: 0, 1: 0}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.7/v/missing`

**Comment by hklarner** [comment]
Hi. Are you sure it fails to create the problem file? The message looks just like a warning.

**Comment by Unaimend** [comment]
![image](https://github.com/hklarner/detection_of_markers_for_discrete_phenotypes/assets/7808379/b9c46637-a6cb-4452-b9e7-65e91a353863)
No files get created :)

**Comment by hklarner** [comment]
Ok, I could reproduce the problem and have fixed it on branch master and in version `1.0.0`.

**Comment by Unaimend** [comment]
Can confirm that it works now
